import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export const dynamic = "force-dynamic";
import { Separator } from "@/components/ui/separator";

const RISK_COLORS: Record<string, string> = {
  low: "bg-green-500/15 text-green-700 border-green-500/25",
  medium: "bg-yellow-500/15 text-yellow-700 border-yellow-500/25",
  high: "bg-orange-500/15 text-orange-700 border-orange-500/25",
  critical: "bg-red-500/15 text-red-700 border-red-500/25",
};

export default async function VerifyPage({
  params,
}: {
  params: Promise<{ verificationId: string }>;
}) {
  const { verificationId } = await params;

  const manifest = await prisma.verificationManifest.findUnique({
    where: { id: verificationId },
  });

  if (!manifest) notFound();

  const report = await prisma.report.findFirst({
    where: { runId: manifest.runId },
  });

  const run = await prisma.verificationRun.findUnique({
    where: { id: manifest.runId },
  });

  const passCount = run
    ? await prisma.finding.count({
        where: { runId: run.id, result: "pass" },
      })
    : 0;

  const failCount = run
    ? await prisma.finding.count({
        where: { runId: run.id, result: "fail" },
      })
    : 0;

  const totalFindings = run
    ? await prisma.finding.count({
        where: { runId: run.id },
      })
    : 0;

  return (
    <div className="flex min-h-screen items-center justify-center bg-background p-4">
      <div className="w-full max-w-lg space-y-6">
        <div className="text-center space-y-2">
          <h1 className="text-2xl font-semibold">Legal Citer</h1>
          <p className="text-sm text-muted-foreground">
            Document Verification Confirmation
          </p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Verification Status</CardTitle>
            <CardDescription>
              This document was verified through Legal Citer.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <dl className="grid grid-cols-2 gap-3 text-sm">
              <dt className="text-muted-foreground">Document Hash</dt>
              <dd className="font-mono text-xs break-all">
                {manifest.documentHash}
              </dd>
              <dt className="text-muted-foreground">Verified</dt>
              <dd>
                {manifest.signedAt
                  ? manifest.signedAt.toLocaleString()
                  : manifest.createdAt.toLocaleString()}
              </dd>
              {report?.riskBand && (
                <>
                  <dt className="text-muted-foreground">Risk Band</dt>
                  <dd>
                    <Badge
                      variant="outline"
                      className={RISK_COLORS[report.riskBand] ?? ""}
                    >
                      {report.riskBand}
                    </Badge>
                  </dd>
                </>
              )}
              {report?.coveragePct != null && (
                <>
                  <dt className="text-muted-foreground">Coverage</dt>
                  <dd>{report.coveragePct.toFixed(1)}%</dd>
                </>
              )}
            </dl>

            <Separator />

            <div className="grid grid-cols-3 gap-4 text-center">
              <div>
                <p className="text-2xl font-semibold">{totalFindings}</p>
                <p className="text-xs text-muted-foreground">Total Checks</p>
              </div>
              <div>
                <p className="text-2xl font-semibold text-green-700">{passCount}</p>
                <p className="text-xs text-muted-foreground">Passed</p>
              </div>
              <div>
                <p className="text-2xl font-semibold text-red-700">{failCount}</p>
                <p className="text-xs text-muted-foreground">Failed</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <p className="text-center text-xs text-muted-foreground">
          This is a verification confirmation generated by Legal Citer.
          It confirms that the document with the above hash was processed.
          This is not a legal certification or guarantee of accuracy.
        </p>
      </div>
    </div>
  );
}
