import { BRAND, publicVerificationUrl } from "@/lib/brand";

export interface ExhibitSection {
  title: string;
  content: Record<string, unknown>;
}

export interface ExhibitHeader {
  organizationName: string;
  title: string;
  date: string;
}

export interface ExhibitFooter {
  verifier: string;
  verificationUrl: string;
  pageNumber: number;
}

export interface ExhibitDocument {
  sections: ExhibitSection[];
  metadata: Record<string, unknown>;
  header: ExhibitHeader;
  footer: ExhibitFooter;
}

export function generatePublicExhibit(params: {
  reportId: string;
  organization: Record<string, unknown>;
  report: Record<string, unknown>;
}): ExhibitDocument {
  const date = new Date().toISOString();

  const summarySection: ExhibitSection = {
    title: "Verification Summary",
    content: {
      reportId: params.reportId,
      riskBand: params.report.riskBand ?? "unknown",
      coveragePct: params.report.coveragePct ?? 0,
      citationCount: params.report.citationCount ?? 0,
      quoteIssues: params.report.quoteIssues ?? 0,
      unresolvedItems: params.report.unresolvedItems ?? 0,
      generatedAt: params.report.generatedAt ?? date,
    },
  };

  const disclaimerSection: ExhibitSection = {
    title: "Disclaimers",
    content: {
      notices: [
        `This report is generated by ${BRAND.product}`,
        "It does not constitute legal advice",
        "Users should independently verify all citations before filing",
      ],
    },
  };

  return {
    sections: [summarySection, disclaimerSection],
    metadata: {
      reportId: params.reportId,
      type: "public_exhibit",
      generatedAt: date,
    },
    header: {
      organizationName: (params.organization?.name as string) ?? "Unknown Organization",
      title: BRAND.artifactSummary,
      date,
    },
    footer: {
      verifier: `Generated by ${BRAND.product}`,
      verificationUrl: publicVerificationUrl(params.reportId),
      pageNumber: 1,
    },
  };
}

export function generatePrivateAppendix(params: {
  reportId: string;
  findings: Record<string, unknown>[];
}): ExhibitDocument {
  const date = new Date().toISOString();

  const itemizedFindings: ExhibitSection = {
    title: "Itemized Findings",
    content: {
      findings: params.findings.map((f) => ({
        id: f.id,
        checkType: f.checkType,
        result: f.result,
        citationText: f.citationText ?? null,
        sourceQueried: f.sourceQueried ?? null,
        snippetUsed: f.snippetUsed ?? null,
        severity: f.severity ?? null,
        isAiAssisted: f.isAiAssisted ?? false,
        metadata: f.metadata ?? null,
      })),
    },
  };

  const evidenceSection: ExhibitSection = {
    title: "Evidence Metadata",
    content: {
      findings: params.findings.map((f) => ({
        id: f.id,
        checkType: f.checkType,
        sourceQueried: f.sourceQueried ?? null,
        snippetUsed: f.snippetUsed ?? null,
        ruleId: f.ruleId ?? null,
        metadata: f.metadata ?? null,
      })),
    },
  };

  const statisticsSection: ExhibitSection = {
    title: "Statistics",
    content: {
      totalFindings: params.findings.length,
      passCount: params.findings.filter((f) => f.result === "pass").length,
      failCount: params.findings.filter((f) => f.result === "fail").length,
      unresolvedCount: params.findings.filter((f) => f.result === "unresolved")
        .length,
      errorCount: params.findings.filter((f) => f.result === "error").length,
      aiAssistedCount: params.findings.filter((f) => f.isAiAssisted).length,
    },
  };

  return {
    sections: [itemizedFindings, evidenceSection, statisticsSection],
    metadata: {
      reportId: params.reportId,
      type: "private_appendix",
      generatedAt: date,
      findingCount: params.findings.length,
    },
    header: {
      organizationName: "",
      title: `${BRAND.artifactSummary} — Private Appendix`,
      date,
    },
    footer: {
      verifier: `Generated by ${BRAND.product}`,
      verificationUrl: publicVerificationUrl(params.reportId),
      pageNumber: 1,
    },
  };
}
